namespace Artemis.Plugins.Games.RocketLeague
{
    public enum RocketLeaguePlaylist
    {
        Duel = 01,
        Doubles = 02,
        Standard = 03,
        Chaos = 04,
        PrivateMatch = 06,
        Season = 07,
        Exhibition = 08,
        Training = 09,
        DuelRanked = 10,
        DoublesRanked = 11,
        StandardRanked = 13,
        SnowDay = 15,
        RocketLabs = 16,
        Hoops = 17,
        Rumble = 18,
        Workshop = 19,
        CustomTrainingEditor = 20,
        CustomTraining = 21,
        TournamentMatchCustom = 22,
        Dropshot = 23,
        LocalMatch = 24,
        ExternalMatchRanked = 26,
        HoopsRanked = 27,
        RumbleRanked = 28,
        DropshotRanked = 29,
        SnowDayRanked = 30,
        GhostHunt = 31,
        BeachBall = 32,
        SpikeRush = 33,
        TournamentMatchAutomatic = 34,
        DropshotRumble = 37,
        Heatseeker = 38,
        BoomerBall = 41,
        HeatseekerDoubles = 43,
        WinterBreakaway = 44,
        Gridiron = 46,
    }
}